.TH "src/err_exit.c" 3 "Mon May 2 2022" "system_call" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/err_exit.c \- Contiene l'implementazione della funzione di stampa degli errori\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'err_exit\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBerrExit\fP (const char *msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contiene l'implementazione della funzione di stampa degli errori\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for system_call from the source code\&.
