.TH "src/semaphore.c" 3 "Mon May 2 2022" "system_call" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/semaphore.c \- Contiene l'implementazione delle funzioni specifiche per la gestione dei SEMAFORI\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'err_exit\&.h'\fP
.br
\fC#include 'semaphore\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Contiene l'implementazione delle funzioni specifiche per la gestione dei SEMAFORI\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for system_call from the source code\&.
